phone_book/urls.py
from django.urls import path
from . views import *

app_name = 'phone_book'


urlpatterns =[
    path('', phone_list, name='phone_list'),
    path('contacts/<slug:slug>/', contact_detail, name='contact_detail'),
    path('search/', contact_search, name='contact_search'),
]

phone_book_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phone_book.urls', namespace='phone_book')),
]

phone_book/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse

phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                             message="Phone number must be entered in the format: '+996777777777'. Up to 15 digits allowed.")


class Contact(models.Model):
    first_name = models.CharField(max_length=20, verbose_name='Фамилия')
    last_name = models.CharField(max_length=20, verbose_name='Имя')
    third_name = models.CharField(max_length=20, null=True, blank=True, verbose_name='Отчество')
    date_of_birth = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    phone_number = models.CharField(validators=[phone_regex], max_length=13, blank=True, verbose_name='Номер телефона',
                                    unique=True, )
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    slug = models.SlugField(max_length=13, unique=True)

    def get_birth_year(self):
        return self.date_of_birth.year

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

    def __str__(self):
        if self.third_name:
            return f'{self.first_name} {self.last_name} {self.third_name}'
        else:
            return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('phone_book:contact_detail', self.slug)

phone_book/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(max_length=50,)

phone_book/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector
from .models import Contact
from .forms import SearchForm


def phone_list(request):
    # phone_list = Contact.objects.all()
    object_list = Contact.objects.all().order_by('first_name', 'last_name', 'third_name')
    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)

    return render(request, 'phone_book/phone_list.html', {'page': page,
                                                          'contacts': contacts})


def contact_detail(request, slug):
    contact = get_object_or_404(Contact, slug=slug)
    return render(request, 'phone_book/contact_detail.html', {'contact': contact})


def contact_search(request):
    form = SearchForm()
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        result = Contact.objects.annotate(
            search=SearchVector('last_name', 'first_name', 'third_name', 'phone_number'),
        ).filter(search=query)
    return render(request, 'phone_book/search.html', {'form': form, 'query': query, 'result': result})

templates/index/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Телефонная книга{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/phone_book.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">
</head>
<body>
<header class="header">
    <div class="header-top">
        <div class="container">
            <div class="header-top-inner">
                <ul class="language">
                    <li>Кырг</li>
                    <li>Рус</li>
                </ul>
                <ul class="header-top-info">
                    <li><a href="{% url 'phone_book:phone_list' %}">Главная</a></li>
                    <li><a href="#">Офисы и терминалы</a></li>
                    <li><a href="#">Частным лицам</a></li>
                    <li><a href="#">Бизнесу</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="header-bottom">
        <div class="container">
            <div class="header-bottom-inner">
                <h1><a href="#" class="logo">Телефонный справочник <a href="#" class="beeline">Beeline</a></a></h1>
                <nav class="main-nav">
                    <ul>
                        <li><a href="{% url 'phone_book:contact_search' %}">Поиск контактов</a></li>
                        <li><a href="{% url 'admin:login' %}" class="login">Войти</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

{% block content %}

{% endblock %}

<footer class="footer">
    <div class="container">
        <div class="footer-inner">
            <div class="info">
                <p>Телефонная книга Beeline 2021</p>
                <p>Зарегистрировано <span>{{ contact_cp.count }}</span> абонентов</p>
            </div>
            <div class="contacts">
                <p>Связаться с нами: <span>+996 777 777 777</span></p>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

templates/phone_book/contact_detail.html
{% extends 'index/index.html' %}

{% block title %}
    {{ contact.first_name }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="contact">
            <a href="{% url 'phone_book:phone_list' %}">< Назад</a>
            <h2>Абонент:</h2>
            <table class="tbl-1">
                <tr>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Отчество</th>
                </tr>
                <tr>
                    <td>{{ contact.first_name }}</td>
                    <td>{{ contact.last_name }}</td>
                    <td>{% if contact.third_name %}{{ contact.third_name }}{% else %}-{% endif %}</td>
                </tr>
            </table>
            <table class="tbl-2">
                <tr>
                    <td>Номер телефона</td>
                    <td>{{ contact.phone_number }}</td>
                </tr>
                <tr>
                    <td>Дата рождения</td>
                    <td>{{ contact.date_of_birth }}</td>
                </tr>
                <tr>
                    <td>Абонент создан</td>
                    <td>{{ contact.created }}</td>
                </tr>
                <tr>
                    <td>Последние изменения</td>
                    <td>{% if contact.updated %}{{ contact.updated }}{% else %}-{% endif %}</td>
                </tr>

            </table>
        </div>
    </div>
{% endblock %}

templates/phone_book/pagination.html
<div class="pagination">
    <div class="container">
        <span class="step-links">
            {% if page.has_previous %}
                <a href="?page={{page.previous_page_number}}">{{page.previous_page_number}}</a>
            {% endif %}
                <span class="current">
            {{ page.number }}
            </span>
                {% if page.has_next %}
                    <a href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a>
                {% endif %}
        </span>
    </div>
</div>

templates/phone_book/phone_list.html
{% extends 'index/index.html' %}

{% block title %}
    Список телефонов
{% endblock %}


{% block content %}

    <div class="container">
        <div class="phone-list">
            <h2>Список номеров зарегистрированных на портале:</h2>
            <ol>
                {% for contact in contacts %}
                    <li>
                        <a href="{% url 'phone_book:contact_detail' contact.slug %}">
                            <span>{{ contact.first_name }}</span>
                            <span>{{ contact.last_name}}</span>
                            <span>{% if contact.third_name %}{{ contact.third_name }}{% endif %}</span>
                        </a>
                    </li>
                {% endfor %}
            </ol>
        </div>
    </div>
    {% include "phone_book/pagination.html" with page=contacts %}

{% endblock %}

templates/phone_book/search.html
{% extends 'index/index.html' %}

{% block title %}
    Поиск
{% endblock %}

{% block content %}

    <div class="container">
        <div class="search-block phone-list">
            {% if query %}
                <h3>Поиск по имени "{{ query }}"</h3>
                <p>
                    {% with results.count as total_results %}
                        Найдены {{ total_results }} результаты: {{ total_results|pluralize }}
                    {% endwith %}
                </p>
                <ol>
                {% for contact in result %}
                    <li><a href="{% url 'phone_book:contact_detail' contact.slug %}">{{ contact.first_name }} {{ contact.last_name }} {% if contact.third_name %}{{ contact.third_name }}
                    {% endif %}</a></li>
                {% empty %}
                    </ol>
                    <p>Абонентов не найдено</p>
                {% endfor %}
                <p><a href="{% url 'phone_book:contact_search' %}">Искать заново</a></p>
            {% else %}
                <h3>Поиск контактов</h3>
                <form action="." method="get">
                    {{ form.query }}
                    <input type="submit" value="Поиск">
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}